d: '2'
fb: Schülerinnen und Schüler
header:
- A1.1 Der Unterricht wird durch Störungen nicht beeinträchtigt.
- A1.2 Die Lernzeit wird effizient genutzt.
- A1.3 Das Unterrichtsklima ist lernförderlich.
- A2.1 Der Unterricht basiert auf Zielen und zu erwerbenden Kompetenzen.
- A2.2 Die Inhalte des Unterrichts werden klar und anschaulich dargestellt.
- A3.2 Die Variation der Lehr- und Lernmethoden ist motivierend.
- A4.1 Beiträge der Schülerinnen und Schüler werden in den Unterricht einbezogen.
- A4.2 Alltags- und Anwendungsbezug sind Elemente des Unterrichts.
- A4.3 Der Unterricht ermöglicht das Erleben eigener Kompetenz.
- A5.1 Der individuelle Lernstand wird erfasst und im Unterricht berücksichtigt.
- A5.2 Rückmeldungen und Unterstützungsangebote fördern den individuellen Lernprozess.
- A5.3 Der Unterricht bietet Möglichkeiten der Selbstbestimmung und Selbstorganisation
  des Lernprozesses.
- A6.1 Im Unterricht wird Wissen vernetzt.
- A6.3 Lernstrategien werden im Unterricht vermittelt und angewandt.
- A6.4 Der Unterricht enthält Übungsphasen und sichert die Ergebnisse.
- B1.1 Formen der Mitbestimmung und Verantwortungsübernahme werden an der Schule praktiziert.
- B1.2 Die Individualität aller wird anerkannt und wertgeschätzt.
- B1.3 Es herrscht ein positives Schulklima.
- B2.1 Die Schule fördert individuelle Interessen und Fähigkeiten der Schülerinnen
  und Schüler.
- B2. 2 Die Schule fördert die Auseinandersetzung mit unterschiedlichen Lebensbereichen.
- B3.1 Die Schule legt Wert auf eine gesunde Lebensführung und Umweltbewusstsein.
- B3.2 Die Schule fördert die selbstbestimmte Teilhabe der Schülerinnen und Schüler
  an der digitalen Gesellschaft.
- B3.3 Die Schule fördert den konstruktiven Umgang mit Konflikten.
- W1.2 Heterogenität wird als Teil der Schulkultur wertgeschätzt und ist im Schulalltag
  erkennbar.
- W1.4 Das pädagogische Handeln im Unterricht berücksichtigt die Heterogenität der
  Schülerinnen und Schüler.
- Nutzung digitaler Geräte - Schülerinnen und Schüler
- W2.4 Zur Gestaltung eines kompetenzorientierten Unterrichts werden digitale Medien
  eingebunden.
- W2.5 Digitale Medien unterstützen die individuelle Förderung und Selbststeuerung
  der Schülerinnen und Schüler.
- W2.6 Die Schule fördert die selbstbestimmte Teilhabe der Schülerinnen und Schüler
  an der digitalen Gesellschaft.
- Schülerinnen und Schüler
meta:
- A11
- A12
- A13
- A21
- A22
- A32
- A41
- A42
- A43
- A51
- A52
- A53
- A61
- A63
- A64
- B11
- B12
- B13
- B21
- B22
- B31
- B32
- B33
- W12
- W14
- W2sus
- W24
- W25
- W26
- ZS
n: '30'
name: Leibniz-Gymnasium Altdorf
num_bars:
- 4
- 3
- 4
- 3
- 2
- 3
- 1
- 3
- 4
- 1
- 4
- 5
- 1
- 7
- 4
- 3
- 2
- 5
- 3
- 4
- 1
- 5
- 2
- 5
- 3
- 1
- 4
- 4
- 5
- 5
snr: '0001'
